---
- name: "Fetch the artifact and extract it"
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Prepare application files"
  become: true
  shell: | 
    cd /home/ubuntu
    mkdir app && tar xzf artifact.tar.gz -C app

- name: "Start the server"
  become: true
  shell: | 
    cd /home/ubuntu/app
    pm2 stop default
    pm2 start npm -- start
