---
- name: "Fetch the artifact and extract it"
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Prepare application files"
  shell: | 
    cd /home/ubuntu
    tar xzf artifact.tar.gz -C .
    echo ENVIRONMENT=development > .env
    echo TYPEORM_CONNECTION=postgres >> .env
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
    echo TYPEORM_HOST=$TYPEORM_HOST >> .env
    echo TYPEORM_PORT=$TYPEORM_PORT >> .env
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
    echo NODE_ENV=development >> ".env"
    npm install && npm run build
    npm audit fix && npm run build


- name: "Start the server"
  shell: | 
    pm2 stop default
    pm2 start npm --name backend -- start
    cd dist
    pm2 start main.js --update-env